FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY services ./services
RUN CGO_ENABLED=0 go build -o /graphshield-worker ./services/worker
FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /graphshield-worker /graphshield-worker
ENTRYPOINT ["/graphshield-worker"]
